# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: test-automation-ci

on:
  pull_request:
    branches:
      - '*'
#      - '!master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run Test
          run: python -m unittest discover tests "*.py" -v
          env:
            TEST_ENV: QA
            HEADLESS: True
        - uses: actions/upload-artifact@v3
          with:
            name: test-artifacts
            path: test_run_results/ # or path/to/artifact